// Must be first: loads server/.env into process.env before anything reads it.
import { requireEnv } from '../config/loadEnv.js';
import mongoose from 'mongoose';

import Product from '../models/Product.js';
import MerchantSettings, { DEFAULT_SETTINGS } from '../models/MerchantSettings.js';

// ──────────────────────────────────────────────────────────────────────────────
// Expanded product catalogue (42 items) — preserves all existing 22 skus and
// their prices exactly so the frontend cart keeps working without any changes.
// ──────────────────────────────────────────────────────────────────────────────

const products = [
  // ── FOOTWEAR ──────────────────────────────────────────────────────────────
  {
    sku: 1,
    name: 'Premium Sneakers',
    brand: 'Strideline',
    category: 'Footwear',
    subcategory: 'Casual Shoes',
    price: 2000,
    originalPrice: 2400,
    costPrice: 1400,
    inventory: 80,
    rating: 4.7,
    reviewCount: 128,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80',
    ],
    description: 'Sleek, comfortable everyday sneakers built for style and performance.',
    features: ['Breathable knit upper', 'Cushioned memory-foam insole', 'Durable rubber outsole', 'Lightweight — 260g per shoe'],
    specifications: { Weight: '260g', Material: 'Knit + Rubber', Closure: 'Lace-up', Sole: 'Rubber' },
    tags: ['sneakers', 'casual', 'everyday', 'comfortable', 'lightweight'],
    colors: ['White', 'Black', 'Grey'],
    sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '6 months manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isNew: false,
    isFeatured: true,
    reviews: [
      { user: 'Aarav M.', rating: 5, title: 'Incredibly comfortable', comment: 'Wore these all day walking around the city — zero blisters. Comfortable and true to size.', verified: true, date: '2025-08-01' },
      { user: 'Priya S.', rating: 5, title: 'Great value', comment: 'Look premium, feel premium. The cushioning is excellent for the price.', verified: true, date: '2025-07-20' },
      { user: 'Rohit K.', rating: 4, title: 'Good but runs slightly narrow', comment: 'Really comfortable once broken in, but I wish they were a touch wider in the toe box.', verified: true, date: '2025-07-10' },
      { user: 'Neha T.', rating: 4, title: 'Stylish and light', comment: 'Very lightweight and the design goes with everything.', verified: false, date: '2025-06-15' },
      { user: 'Vikram R.', rating: 5, title: 'Buying a second pair', comment: 'Six months in and they still look new. Quality build.', verified: true, date: '2025-06-01' },
    ],
  },
  {
    sku: 8,
    name: 'Running Socks',
    brand: 'Strideline',
    category: 'Footwear',
    subcategory: 'Socks',
    price: 400,
    originalPrice: 499,
    costPrice: 150,
    inventory: 300,
    rating: 4.2,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&q=80',
    description: 'Cushioned arch-support running socks with moisture-wicking fabric.',
    features: ['Arch compression support', 'Moisture-wicking fabric', 'Anti-blister heel tab', 'Pack of 3 pairs'],
    specifications: { Pack: '3 pairs', Material: '80% Cotton, 20% Spandex', Type: 'Ankle length' },
    tags: ['socks', 'running', 'sports', 'moisture-wicking', 'arch-support'],
    colors: ['White', 'Black', 'Grey'],
    sizes: ['S (UK 5-7)', 'M (UK 8-10)', 'L (UK 11-13)'],
    delivery: 'Free delivery in 2–4 working days',
    warranty: '30-day quality guarantee',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Meera G.', rating: 4, title: 'Very comfortable', comment: 'Great for long runs. No slipping or bunching.', verified: true, date: '2025-07-05' },
      { user: 'Arjun L.', rating: 4, title: 'Good quality', comment: 'Durable and comfortable. Good value in a pack.', verified: true, date: '2025-06-20' },
    ],
  },
  {
    sku: 18,
    name: 'Trail Running Shoes',
    brand: 'Strideline',
    category: 'Footwear',
    subcategory: 'Running Shoes',
    price: 2600,
    originalPrice: 3200,
    costPrice: 1500,
    inventory: 65,
    rating: 4.6,
    reviewCount: 176,
    image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80',
    description: 'Grippy, responsive trail shoes with a rock plate and breathable mesh.',
    features: ['Rock plate protection', 'Lugged rubber outsole', 'Breathable mesh upper', 'Cushioned midsole'],
    specifications: { Weight: '310g', Drop: '8mm', Material: 'Mesh + TPU', Closure: 'Lace-up' },
    tags: ['trail', 'running', 'outdoor', 'hiking', 'sports'],
    colors: ['Blue', 'Green', 'Black'],
    sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Sanjay B.', rating: 5, title: 'Excellent grip', comment: 'Best trail shoes I\'ve worn. Confident on wet rocks and loose gravel.', verified: true, date: '2025-08-10' },
      { user: 'Pooja N.', rating: 4, title: 'Good but heavy', comment: 'Grip is great, slightly heavy for racing but perfect for training.', verified: true, date: '2025-07-25' },
    ],
  },

  // ── CLOTHING ──────────────────────────────────────────────────────────────
  {
    sku: 2,
    name: 'Oversized T-Shirt',
    brand: 'Everyday Co',
    category: 'Clothing',
    subcategory: 'T-Shirts',
    price: 800,
    originalPrice: 999,
    costPrice: 350,
    inventory: 200,
    rating: 4.5,
    reviewCount: 214,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
    description: 'Premium cotton oversized tee — the perfect everyday wardrobe staple.',
    features: ['100% combed cotton, 240 GSM', 'Relaxed oversized fit', 'Pre-shrunk, holds shape after washes', 'Unisex sizing'],
    specifications: { Material: '100% Cotton', GSM: '240', Fit: 'Oversized', Neck: 'Round' },
    tags: ['t-shirt', 'cotton', 'oversized', 'casual', 'unisex'],
    colors: ['White', 'Black', 'Olive', 'Navy', 'Beige'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    delivery: 'Free delivery in 2–4 working days',
    warranty: '30-day quality guarantee',
    returnPolicy: '15-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Simran D.', rating: 5, title: 'Perfect drape', comment: 'The oversized fit is exactly right — not a tent, just relaxed.', verified: true, date: '2025-07-30' },
      { user: 'Karan P.', rating: 4, title: 'Soft, slightly long', comment: 'Great cotton quality. A little longer than expected but I like it.', verified: true, date: '2025-07-10' },
      { user: 'Ananya G.', rating: 5, title: 'Bought three colours', comment: 'Held up perfectly after many washes, no shrinkage.', verified: true, date: '2025-06-20' },
    ],
  },
  {
    sku: 20,
    name: 'Slim-Fit Jeans',
    brand: 'Everyday Co',
    category: 'Clothing',
    subcategory: 'Jeans',
    price: 1600,
    originalPrice: 1999,
    costPrice: 700,
    inventory: 160,
    rating: 4.4,
    reviewCount: 231,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80',
    description: 'Stretch-denim slim-fit jeans that hold their shape all day.',
    features: ['2% elastane stretch denim', 'Slim tapered leg', 'Mid-rise waist', '5-pocket design'],
    specifications: { Material: '98% Cotton, 2% Elastane', Fit: 'Slim', Rise: 'Mid-rise', Wash: 'Dark Indigo' },
    tags: ['jeans', 'denim', 'slim-fit', 'stretch', 'casual'],
    colors: ['Dark Indigo', 'Light Blue', 'Black'],
    sizes: ['28x30', '30x30', '32x32', '34x32', '36x32'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '30-day quality guarantee',
    returnPolicy: '15-day easy returns',
    reviews: [
      { user: 'Rajan M.', rating: 5, title: 'Perfect fit', comment: 'True to size and very comfortable. The stretch is just right.', verified: true, date: '2025-08-05' },
    ],
  },
  {
    sku: 21,
    name: 'Zip Hoodie',
    brand: 'Everyday Co',
    category: 'Clothing',
    subcategory: 'Hoodies',
    price: 1500,
    originalPrice: 1899,
    costPrice: 650,
    inventory: 120,
    rating: 4.6,
    reviewCount: 187,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&q=80',
    description: 'Heavyweight brushed-fleece zip hoodie with a soft-lined hood.',
    features: ['340 GSM brushed fleece', 'YKK zip', 'Kangaroo pocket', 'Unisex fit'],
    specifications: { Material: '80% Cotton, 20% Polyester', GSM: '340', Closure: 'Full-zip', Fit: 'Regular' },
    tags: ['hoodie', 'zip', 'fleece', 'warm', 'casual', 'winter'],
    colors: ['Charcoal', 'Navy', 'Olive', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '30-day quality guarantee',
    returnPolicy: '15-day easy returns',
    reviews: [
      { user: 'Divya K.', rating: 5, title: 'So cozy', comment: 'The fleece lining is incredibly soft. My go-to hoodie now.', verified: true, date: '2025-08-15' },
    ],
  },
  {
    sku: 22,
    name: 'Denim Jacket',
    brand: 'Denim Theory',
    category: 'Clothing',
    subcategory: 'Jackets',
    price: 2400,
    originalPrice: 2999,
    costPrice: 1100,
    inventory: 70,
    rating: 4.5,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=600&q=80',
    description: 'Classic rigid-denim trucker jacket that breaks in beautifully over time.',
    features: ['100% rigid denim', 'Chest pockets', 'Metal button closure', 'Structured trucker fit'],
    specifications: { Material: '100% Cotton Denim', Fit: 'Regular', Closure: 'Button', Weight: 'Heavy-weight' },
    tags: ['denim jacket', 'trucker', 'casual', 'unisex', 'outerwear'],
    colors: ['Light Blue', 'Dark Indigo', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '30-day quality guarantee',
    returnPolicy: '15-day easy returns',
    reviews: [
      { user: 'Aryan T.', rating: 5, title: 'Classic piece', comment: 'Great quality denim. Gets better with every wear.', verified: true, date: '2025-07-20' },
    ],
  },

  // ── ELECTRONICS ──────────────────────────────────────────────────────────
  {
    sku: 5,
    name: 'Wireless Headphones',
    brand: 'Nimbus',
    category: 'Electronics',
    subcategory: 'Headphones',
    price: 2500,
    originalPrice: 2999,
    costPrice: 1500,
    inventory: 60,
    rating: 4.8,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    description: '40-hour battery, active noise cancellation, studio-quality sound.',
    features: ['40-hour playtime', 'Active noise cancellation', '40mm drivers', 'Foldable design', 'USB-C charging'],
    specifications: { 'Driver Size': '40mm', 'Battery Life': '40 hours', 'Charging': 'USB-C', 'Connectivity': 'Bluetooth 5.2', 'ANC': 'Yes', 'Weight': '250g' },
    tags: ['headphones', 'wireless', 'ANC', 'bluetooth', 'music', 'noise cancelling'],
    colors: ['Midnight Black', 'Pearl White', 'Midnight Blue'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Arnav S.', rating: 5, title: 'Best headphones I\'ve owned', comment: 'ANC is incredible, sound quality is studio level.', verified: true, date: '2025-08-12' },
      { user: 'Tanvi P.', rating: 5, title: 'Worth every rupee', comment: 'Battery lasts me almost a week with moderate use.', verified: true, date: '2025-08-01' },
    ],
  },
  {
    sku: 6,
    name: 'Smart Watch',
    brand: 'Nimbus',
    category: 'Electronics',
    subcategory: 'Smartwatches',
    price: 3000,
    originalPrice: 3499,
    costPrice: 1800,
    inventory: 45,
    rating: 4.7,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
    description: 'Health tracking, notifications, and GPS in a sleek aluminium build.',
    features: ['GPS tracking', 'Heart rate + SpO2 sensor', '7-day battery', 'IP68 waterproof', '1.4" AMOLED display'],
    specifications: { Display: '1.4" AMOLED', Battery: '7 days', 'Water Resistance': 'IP68', GPS: 'Built-in', Sensors: 'HR, SpO2, Accelerometer' },
    tags: ['smartwatch', 'fitness', 'GPS', 'health', 'wearable', 'AMOLED'],
    colors: ['Silver', 'Graphite', 'Rose Gold'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Kiran M.', rating: 5, title: 'Perfect fitness companion', comment: 'GPS accuracy is excellent. Battery really does last 7 days.', verified: true, date: '2025-08-08' },
    ],
  },
  {
    sku: 9,
    name: 'UltraBook 14 Laptop',
    brand: 'Volt',
    category: 'Electronics',
    subcategory: 'Laptops',
    price: 45000,
    originalPrice: 52000,
    costPrice: 34000,
    inventory: 30,
    rating: 4.6,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
    description: 'Thin-and-light 14" laptop with an all-day battery and a crisp 2.2K display.',
    features: ['14" 2.2K IPS display', '12-hour battery', '512GB NVMe SSD', '16GB LPDDR5 RAM', 'Fingerprint sensor'],
    specifications: { Display: '14" 2.2K IPS', RAM: '16GB LPDDR5', Storage: '512GB NVMe SSD', Processor: 'Octa-core 3.5GHz', Battery: '65Wh', OS: 'Windows 11', Weight: '1.35kg' },
    tags: ['laptop', 'ultrabook', 'thin', 'light', 'SSD', '16GB RAM', 'portable'],
    colors: ['Space Grey', 'Silver'],
    delivery: 'Free delivery in 5–7 working days',
    warranty: '1 year manufacturer warranty + 1 year extended',
    returnPolicy: '7-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Nikhil A.', rating: 5, title: 'Incredible build quality', comment: 'The display is stunning and battery life is genuinely all-day.', verified: true, date: '2025-08-10' },
      { user: 'Sneha R.', rating: 4, title: 'Great but pricey', comment: 'Excellent performance but wish it had more ports.', verified: true, date: '2025-07-28' },
    ],
  },
  {
    sku: 10,
    name: 'Wireless Mouse',
    brand: 'Volt',
    category: 'Electronics',
    subcategory: 'Peripherals',
    price: 700,
    originalPrice: 999,
    costPrice: 300,
    inventory: 220,
    rating: 4.4,
    reviewCount: 176,
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&q=80',
    description: 'Silent-click wireless mouse with a precise sensor and months of battery.',
    features: ['Silent click switches', '2400 DPI optical sensor', '18-month battery life', '2.4GHz wireless', 'Ambidextrous design'],
    specifications: { DPI: 'Up to 2400', Connectivity: '2.4GHz Wireless', Battery: 'AAA × 1, 18 months', Buttons: '3', Weight: '100g' },
    tags: ['mouse', 'wireless', 'silent', 'office', 'computer', 'peripheral'],
    colors: ['Black', 'White'],
    delivery: 'Free delivery in 2–4 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Aditya K.', rating: 4, title: 'Great value', comment: 'Silent clicks are a game changer in a quiet office.', verified: true, date: '2025-07-15' },
    ],
  },
  {
    sku: 11,
    name: 'Mechanical Keyboard',
    brand: 'Volt',
    category: 'Electronics',
    subcategory: 'Peripherals',
    price: 2200,
    originalPrice: 2799,
    costPrice: 1200,
    inventory: 90,
    rating: 4.6,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&q=80',
    description: 'Compact hot-swappable mechanical keyboard with tactile switches and backlight.',
    features: ['Hot-swappable switches', 'Per-key RGB backlight', 'TKL 87-key layout', 'USB-C detachable cable', 'Aluminum top plate'],
    specifications: { Layout: 'TKL 87-key', Switches: 'Tactile (Brown)', Backlight: 'RGB per-key', Connection: 'USB-C', Material: 'Aluminum + ABS' },
    tags: ['keyboard', 'mechanical', 'hot-swappable', 'RGB', 'gaming', 'typing'],
    colors: ['Space Grey', 'White'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Rahul D.', rating: 5, title: 'Best keyboard at this price', comment: 'Hot-swap is flawless. Tactile feel is satisfying without being too loud.', verified: true, date: '2025-08-03' },
    ],
  },
  {
    sku: 13,
    name: 'Aurora Smartphone X',
    brand: 'Aurora',
    category: 'Electronics',
    subcategory: 'Smartphones',
    price: 28000,
    originalPrice: 31000,
    costPrice: 21000,
    inventory: 40,
    rating: 4.7,
    reviewCount: 512,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80',
    description: '6.5" AMOLED smartphone with a triple camera, fast charging and 5G.',
    features: ['6.5" 120Hz AMOLED', '48MP triple camera', '5000mAh + 67W fast charge', '5G connectivity', '8GB RAM / 128GB storage'],
    specifications: { Display: '6.5" 120Hz AMOLED', Processor: 'Octa-core 2.8GHz', RAM: '8GB', Storage: '128GB', Camera: '48+12+5MP', Battery: '5000mAh', Charging: '67W Fast Charge', Network: '5G' },
    tags: ['smartphone', '5G', 'AMOLED', 'fast charging', 'triple camera', 'mobile'],
    colors: ['Midnight Black', 'Aurora Blue', 'Starlight White'],
    sizes: ['128GB', '256GB'],
    delivery: 'Free delivery in 2–4 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Vikas S.', rating: 5, title: 'Flagship killer', comment: 'Camera quality rivals phones twice the price.', verified: true, date: '2025-08-14' },
      { user: 'Riya B.', rating: 4, title: 'Fast and beautiful', comment: '67W charging fills it in 40 minutes. Screen is gorgeous.', verified: true, date: '2025-08-02' },
    ],
  },
  {
    sku: 15,
    name: 'Wireless Earbuds',
    brand: 'Nimbus',
    category: 'Electronics',
    subcategory: 'Earbuds',
    price: 1800,
    originalPrice: 2299,
    costPrice: 900,
    inventory: 150,
    rating: 4.5,
    reviewCount: 389,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80',
    description: 'Compact true-wireless earbuds with ANC and a pocketable charging case.',
    features: ['Active noise cancellation', '8h playback + 24h with case', 'IPX5 sweat-resistant', 'Touch controls', 'Transparency mode'],
    specifications: { 'Driver Size': '11mm', 'Battery (earbuds)': '8 hours', 'Battery (case)': '24 hours total', 'ANC': 'Yes', 'Water Resistance': 'IPX5', 'Connectivity': 'Bluetooth 5.3' },
    tags: ['earbuds', 'TWS', 'ANC', 'wireless', 'music', 'noise cancelling'],
    colors: ['Pearl White', 'Graphite Black', 'Sage Green'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Mohit J.', rating: 5, title: 'Excellent ANC', comment: 'ANC is almost on par with premium brands at half the price.', verified: true, date: '2025-08-11' },
    ],
  },

  // ── ACCESSORIES ──────────────────────────────────────────────────────────
  {
    sku: 3,
    name: 'Classic Cap',
    brand: 'Everyday Co',
    category: 'Accessories',
    subcategory: 'Caps & Hats',
    price: 500,
    originalPrice: 699,
    costPrice: 200,
    inventory: 150,
    rating: 4.3,
    reviewCount: 89,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&q=80',
    description: 'Structured 6-panel cap in durable twill — clean, minimal, timeless.',
    features: ['6-panel construction', 'Pre-curved brim', 'Adjustable strap', '100% cotton twill'],
    specifications: { Material: '100% Cotton Twill', Closure: 'Adjustable Snapback', Brim: 'Pre-curved', Panel: '6-panel' },
    tags: ['cap', 'hat', 'casual', 'baseball cap', 'unisex'],
    colors: ['Black', 'Navy', 'Olive', 'Beige', 'White'],
    delivery: 'Free delivery in 2–4 working days',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Jay P.', rating: 4, title: 'Clean and minimal', comment: 'Exactly what I wanted. No logos, just clean.', verified: true, date: '2025-07-18' },
    ],
  },
  {
    sku: 4,
    name: 'Leather Wallet',
    brand: 'Craftline',
    category: 'Accessories',
    subcategory: 'Wallets',
    price: 1200,
    originalPrice: 1499,
    costPrice: 600,
    inventory: 95,
    rating: 4.6,
    reviewCount: 176,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80',
    description: 'Full-grain leather slim wallet with RFID blocking and card slots.',
    features: ['Full-grain leather', 'RFID blocking', '6 card slots', 'Slim profile (8mm)'],
    specifications: { Material: 'Full-grain Leather', 'RFID Block': 'Yes', 'Card Slots': '6', Dimensions: '11 × 8 × 0.8 cm', Color: 'Tan / Black / Dark Brown' },
    tags: ['wallet', 'leather', 'RFID', 'slim', 'men', 'gift'],
    colors: ['Tan', 'Dark Brown', 'Black'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Siddharth G.', rating: 5, title: 'Excellent craftsmanship', comment: 'Feels and looks expensive. Great gift option too.', verified: true, date: '2025-07-22' },
    ],
  },
  {
    sku: 14,
    name: 'Phone Case',
    brand: 'Aurora',
    category: 'Accessories',
    subcategory: 'Phone Cases',
    price: 600,
    originalPrice: 799,
    costPrice: 200,
    inventory: 300,
    rating: 4.3,
    reviewCount: 264,
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&q=80',
    description: 'Shock-absorbing clear case with raised camera and screen bezels.',
    features: ['Military-grade drop protection', 'Crystal clear back', 'Raised camera + screen bezels', 'Wireless charging compatible'],
    specifications: { Material: 'Polycarbonate + TPU', 'Drop Protection': 'MIL-STD-810G', Compatibility: 'Aurora Smartphone X', 'Wireless Charging': 'Compatible' },
    tags: ['phone case', 'clear case', 'protection', 'shock-absorbing'],
    colors: ['Clear', 'Matte Black', 'Frosted Blue'],
    delivery: 'Free delivery in 2–4 working days',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Prachi S.', rating: 4, title: 'Good protection', comment: 'Survived two drops. Still perfectly clear, no yellowing after 2 months.', verified: true, date: '2025-07-30' },
    ],
  },

  // ── LIFESTYLE / BAGS ──────────────────────────────────────────────────────
  {
    sku: 7,
    name: 'Casual Backpack',
    brand: 'Craftline',
    category: 'Bags',
    subcategory: 'Backpacks',
    price: 1500,
    originalPrice: 1899,
    costPrice: 800,
    inventory: 70,
    rating: 4.4,
    reviewCount: 153,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    description: 'Lightweight 25L pack with laptop sleeve and anti-theft hidden pocket.',
    features: ['25L capacity', '15" padded laptop sleeve', 'Anti-theft hidden back pocket', 'USB charging port', 'Water-resistant 600D polyester'],
    specifications: { Capacity: '25L', 'Laptop Sleeve': 'Up to 15"', Material: '600D Polyester', 'USB Port': 'Yes', Weight: '700g' },
    tags: ['backpack', 'laptop bag', 'travel', 'daily carry', 'anti-theft'],
    colors: ['Black', 'Grey', 'Navy'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '6 months manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Akash V.', rating: 5, title: 'Perfect daily bag', comment: 'Very well organized. The anti-theft pocket is cleverly placed.', verified: true, date: '2025-08-05' },
    ],
  },
  {
    sku: 12,
    name: 'Laptop Sleeve',
    brand: 'Craftline',
    category: 'Bags',
    subcategory: 'Laptop Bags',
    price: 900,
    originalPrice: 1199,
    costPrice: 400,
    inventory: 130,
    rating: 4.5,
    reviewCount: 87,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80',
    description: 'Padded 14" laptop sleeve in water-resistant felt with a slim front pocket.',
    features: ['10mm foam padding', 'Water-resistant wool-blend felt', 'Slim front accessory pocket', 'Velcro closure'],
    specifications: { Fits: 'Up to 14" laptops', Material: 'Wool-blend Felt', Padding: '10mm foam', Closure: 'Velcro' },
    tags: ['laptop sleeve', 'felt', 'protective', 'sleeve', 'case'],
    colors: ['Charcoal', 'Camel', 'Navy'],
    delivery: 'Free delivery in 2–4 working days',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Ishaan M.', rating: 5, title: 'Premium feel', comment: 'Looks and feels expensive. Laptop slides in perfectly.', verified: true, date: '2025-07-28' },
    ],
  },
  {
    sku: 16,
    name: 'Insulated Water Bottle',
    brand: 'Trailhead',
    category: 'Lifestyle',
    subcategory: 'Bottles & Hydration',
    price: 800,
    originalPrice: 1099,
    costPrice: 350,
    inventory: 180,
    rating: 4.6,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=600&q=80',
    description: 'Double-wall vacuum bottle that keeps drinks cold 24h or hot 12h.',
    features: ['Double-wall vacuum insulation', 'Cold 24 hours / Hot 12 hours', 'BPA-free stainless steel', 'Leak-proof lid', '750ml capacity'],
    specifications: { Capacity: '750ml', Material: '18/8 Stainless Steel', 'BPA-free': 'Yes', 'Cold': '24 hours', 'Hot': '12 hours', Lid: 'Screw-top leak-proof' },
    tags: ['water bottle', 'insulated', 'stainless steel', 'BPA-free', 'gym', 'outdoor'],
    colors: ['Midnight Black', 'Sage Green', 'Arctic White', 'Rust Orange'],
    delivery: 'Free delivery in 2–4 working days',
    warranty: 'Lifetime warranty',
    returnPolicy: '30-day easy returns',
    reviews: [
      { user: 'Anisha B.', rating: 5, title: 'Keeps drinks cold all day', comment: 'Still cold after 8 hours in a hot office. Impressive.', verified: true, date: '2025-08-10' },
    ],
  },
  {
    sku: 17,
    name: 'Travel Organizer',
    brand: 'Trailhead',
    category: 'Lifestyle',
    subcategory: 'Travel Accessories',
    price: 700,
    originalPrice: 999,
    costPrice: 300,
    inventory: 140,
    rating: 4.4,
    reviewCount: 112,
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600&q=80',
    description: 'Packing cube set with cable pouch to keep your bag tidy on trips.',
    features: ['Set of 3 packing cubes', 'Includes cable organizer pouch', 'Mesh top visibility', 'Compression zipper'],
    specifications: { Set: '3 cubes + 1 pouch', Material: 'Ripstop Nylon', Sizes: 'S, M, L', Compression: 'Double-zip' },
    tags: ['travel', 'packing cubes', 'organizer', 'luggage', 'trip'],
    colors: ['Navy', 'Olive', 'Grey'],
    delivery: 'Free delivery in 3–5 working days',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Shalini R.', rating: 4, title: 'Great for travel', comment: 'Makes packing and finding things so much easier.', verified: true, date: '2025-07-25' },
    ],
  },
  {
    sku: 19,
    name: 'Gym Duffel Bag',
    brand: 'Strideline',
    category: 'Bags',
    subcategory: 'Duffel Bags',
    price: 1400,
    originalPrice: 1799,
    costPrice: 700,
    inventory: 85,
    rating: 4.4,
    reviewCount: 94,
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&q=80',
    description: '40L duffel with a ventilated shoe compartment and a wet pocket.',
    features: ['40L capacity', 'Ventilated shoe compartment', 'Waterproof wet pocket', 'Padded shoulder strap', 'Water-resistant base'],
    specifications: { Capacity: '40L', Material: 'Polyester', 'Shoe Compartment': 'Ventilated', 'Wet Pocket': 'Yes', Weight: '900g' },
    tags: ['duffel bag', 'gym bag', 'sports', 'travel bag', 'fitness'],
    colors: ['Black', 'Grey/Red', 'Navy'],
    delivery: 'Free delivery in 3–5 working days',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Harsh S.', rating: 4, title: 'Perfect gym bag', comment: 'Size is ideal, the shoe compartment is really useful.', verified: true, date: '2025-07-20' },
    ],
  },

  // ── NEW PRODUCTS — MOBILES / LAPTOPS ─────────────────────────────────────
  {
    sku: 23,
    name: 'Nova Pro 5G',
    brand: 'Nova',
    category: 'Electronics',
    subcategory: 'Smartphones',
    price: 18999,
    originalPrice: 22000,
    costPrice: 14000,
    inventory: 55,
    rating: 4.5,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80',
    description: 'Compact 5G smartphone with a 64MP camera and 33W fast charging.',
    features: ['6.1" FHD+ 90Hz display', '64MP OIS camera', '33W fast charging', '4500mAh battery', '6GB RAM / 128GB storage'],
    specifications: { Display: '6.1" FHD+ 90Hz', RAM: '6GB', Storage: '128GB', Camera: '64MP + 8MP + 2MP', Battery: '4500mAh', Charging: '33W', Network: '5G' },
    tags: ['smartphone', '5G', 'compact', '64MP', 'fast charging', 'mobile'],
    colors: ['Starlight Blue', 'Midnight Black', 'Frost White'],
    delivery: 'Free delivery in 2–4 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isNew: true,
    reviews: [
      { user: 'Rahul M.', rating: 5, title: 'Best mid-ranger', comment: 'Camera is outstanding. Fast and smooth.', verified: true, date: '2025-08-15' },
    ],
  },
  {
    sku: 24,
    name: 'Apex Gaming Laptop',
    brand: 'Volt',
    category: 'Electronics',
    subcategory: 'Laptops',
    price: 68000,
    originalPrice: 79999,
    costPrice: 52000,
    inventory: 20,
    rating: 4.7,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=80',
    description: '15.6" gaming laptop with a dedicated GPU, 144Hz display and RGB keyboard.',
    features: ['15.6" FHD 144Hz display', 'Dedicated 8GB GPU', '32GB DDR5 RAM', '1TB NVMe SSD', 'Per-key RGB keyboard', 'Advanced cooling system'],
    specifications: { Display: '15.6" FHD 144Hz', RAM: '32GB DDR5', Storage: '1TB NVMe SSD', GPU: '8GB GDDR6', Processor: '12-core', Battery: '99Wh', OS: 'Windows 11', Weight: '2.1kg' },
    tags: ['gaming laptop', 'GPU', '144Hz', 'RGB', '32GB RAM', 'gaming', 'esports'],
    colors: ['Stealth Black'],
    delivery: 'Free delivery in 5–7 working days',
    warranty: '1 year manufacturer warranty + on-site service',
    returnPolicy: '7-day easy returns',
    isNew: true,
    isFeatured: true,
    reviews: [
      { user: 'Yash G.', rating: 5, title: 'Insane performance', comment: 'Handles every game at max settings. Cooling is excellent.', verified: true, date: '2025-08-12' },
    ],
  },

  // ── NEW PRODUCTS — BEAUTY / PERSONAL CARE ────────────────────────────────
  {
    sku: 25,
    name: 'Vitamin C Serum',
    brand: 'GlowLab',
    category: 'Beauty',
    subcategory: 'Skincare',
    price: 599,
    originalPrice: 799,
    costPrice: 250,
    inventory: 200,
    rating: 4.6,
    reviewCount: 445,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    description: '20% Vitamin C brightening serum with hyaluronic acid for glowing skin.',
    features: ['20% Vitamin C concentration', 'Hyaluronic acid for hydration', 'Reduces dark spots & pigmentation', 'Fragrance-free, dermatologist tested'],
    specifications: { Volume: '30ml', 'Vitamin C': '20%', 'Key Ingredient': 'L-Ascorbic Acid + HA', 'Skin Type': 'All skin types', 'Fragrance': 'Fragrance-free' },
    tags: ['vitamin C', 'serum', 'brightening', 'skincare', 'glow', 'hyaluronic acid'],
    delivery: 'Free delivery in 2–4 working days',
    warranty: '30-day satisfaction guarantee',
    returnPolicy: '15-day easy returns',
    isNew: false,
    isFeatured: true,
    reviews: [
      { user: 'Aditi R.', rating: 5, title: 'Visible results in 2 weeks', comment: 'Dark spots noticeably lighter. Skin feels smoother.', verified: true, date: '2025-08-08' },
      { user: 'Preeti K.', rating: 4, title: 'Good but smells faintly medicinal', comment: 'Works well but the scent can be strong. Results are worth it.', verified: true, date: '2025-07-25' },
    ],
  },
  {
    sku: 26,
    name: 'Beard Grooming Kit',
    brand: 'GlowLab',
    category: 'Beauty',
    subcategory: 'Men\'s Grooming',
    price: 799,
    originalPrice: 999,
    costPrice: 350,
    inventory: 120,
    rating: 4.4,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&q=80',
    description: 'Complete beard kit: oil, balm, wooden comb and boar-bristle brush.',
    features: ['100% natural beard oil (30ml)', 'Shaping beard balm (50g)', 'Sandalwood beard comb', 'Boar-bristle beard brush'],
    specifications: { 'Contents': 'Oil 30ml + Balm 50g + Comb + Brush', 'Oil Base': 'Jojoba + Argan', 'Scent': 'Cedarwood', 'Suitable for': 'All beard types' },
    tags: ['beard', 'grooming', 'beard oil', 'men', 'gift', 'kit'],
    delivery: 'Free delivery in 2–4 working days',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Sachin P.', rating: 5, title: 'Perfect gift for men', comment: 'The oil has a great scent and the comb is high quality.', verified: true, date: '2025-07-20' },
    ],
  },
  {
    sku: 27,
    name: 'Matte Lipstick Set',
    brand: 'GlowLab',
    category: 'Beauty',
    subcategory: 'Makeup',
    price: 499,
    originalPrice: 699,
    costPrice: 180,
    inventory: 180,
    rating: 4.3,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1586495777744-4e6232bf4e91?w=600&q=80',
    description: 'Set of 5 long-lasting matte lipsticks in versatile everyday shades.',
    features: ['5 shades in one set', 'Up to 12-hour wear', 'Non-drying formula', 'Cruelty-free & vegan'],
    specifications: { 'Shades': '5 (Nude, Rose, Mauve, Berry, Red)', 'Finish': 'Matte', 'Wear': '12 hours', 'Cruelty-free': 'Yes', 'Vegan': 'Yes' },
    tags: ['lipstick', 'matte', 'makeup', 'beauty', 'set', 'long-lasting'],
    delivery: 'Free delivery in 2–4 working days',
    returnPolicy: '7-day easy returns',
    isNew: true,
    reviews: [
      { user: 'Nisha T.', rating: 4, title: 'Great shades', comment: 'All five shades are wearable. Lasts most of the day.', verified: true, date: '2025-08-01' },
    ],
  },

  // ── NEW PRODUCTS — HOME / KITCHEN ─────────────────────────────────────────
  {
    sku: 28,
    name: 'Stainless Steel Cookware Set',
    brand: 'HomeChef',
    category: 'Home',
    subcategory: 'Cookware',
    price: 2999,
    originalPrice: 3999,
    costPrice: 1800,
    inventory: 40,
    rating: 4.5,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
    description: '5-piece tri-ply stainless steel cookware set — non-stick, oven-safe.',
    features: ['5-piece set: 2 pots + 2 pans + 1 steamer', 'Tri-ply construction', 'Induction compatible', 'Oven-safe up to 230°C', 'Dishwasher safe'],
    specifications: { Pieces: '5', Material: 'Tri-ply Stainless Steel', 'Induction': 'Yes', 'Oven-safe': 'Up to 230°C', 'Dishwasher': 'Safe' },
    tags: ['cookware', 'pots', 'pans', 'kitchen', 'stainless steel', 'induction'],
    delivery: 'Free delivery in 5–7 working days',
    warranty: '2 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Kavita M.', rating: 5, title: 'Excellent quality', comment: 'Heats evenly and cleans up easily. Worth every rupee.', verified: true, date: '2025-07-28' },
    ],
  },
  {
    sku: 29,
    name: 'Air Purifier Pro',
    brand: 'CleanAir',
    category: 'Home',
    subcategory: 'Air Purifiers',
    price: 8999,
    originalPrice: 11999,
    costPrice: 6000,
    inventory: 25,
    rating: 4.7,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80',
    description: 'HEPA H13 air purifier covering 400 sq ft. Removes 99.97% of allergens.',
    features: ['HEPA H13 filter', 'Covers up to 400 sq ft', 'Removes 99.97% particles', 'Silent mode (20dB)', 'Air quality indicator'],
    specifications: { 'Filter': 'HEPA H13', 'Coverage': '400 sq ft', 'Noise': '20–52dB', 'CADR': '200 m³/h', 'Filter Life': '6–8 months' },
    tags: ['air purifier', 'HEPA', 'allergen', 'clean air', 'home', 'health'],
    delivery: 'Free delivery in 5–7 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isNew: true,
    isFeatured: true,
    reviews: [
      { user: 'Sunita G.', rating: 5, title: 'Breathing easier', comment: 'Huge difference in air quality. Silent mode is genuinely silent.', verified: true, date: '2025-08-10' },
    ],
  },
  {
    sku: 30,
    name: 'Smart LED Strip Lights',
    brand: 'HomeChef',
    category: 'Home',
    subcategory: 'Lighting',
    price: 899,
    originalPrice: 1299,
    costPrice: 400,
    inventory: 200,
    rating: 4.4,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description: '5-metre Wi-Fi LED strip with 16 million colours — app and voice controlled.',
    features: ['5 metre length', '16 million colours + warm/cool white', 'Wi-Fi + App control', 'Works with Alexa & Google Home', 'Music sync mode'],
    specifications: { Length: '5 metres', 'Colors': '16 million', Connectivity: 'Wi-Fi 2.4GHz', Compatibility: 'Alexa, Google Home', 'Power': '24W' },
    tags: ['LED strip', 'smart light', 'ambient', 'RGB', 'Wi-Fi', 'room decor'],
    delivery: 'Free delivery in 3–5 working days',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Dhruv K.', rating: 4, title: 'Great for ambiance', comment: 'App is easy to use, colors are vivid. Music sync is fun.', verified: true, date: '2025-08-05' },
    ],
  },

  // ── NEW PRODUCTS — SPORTS ─────────────────────────────────────────────────
  {
    sku: 31,
    name: 'Yoga Mat Pro',
    brand: 'FitCore',
    category: 'Sports',
    subcategory: 'Yoga & Fitness',
    price: 1299,
    originalPrice: 1799,
    costPrice: 600,
    inventory: 150,
    rating: 4.7,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80',
    description: '6mm thick TPE yoga mat with superior grip and alignment guides.',
    features: ['6mm TPE cushioning', 'Non-slip surface both sides', 'Alignment guide lines', 'Carrying strap included', 'Eco-friendly TPE material'],
    specifications: { Thickness: '6mm', Material: 'TPE', Dimensions: '183 × 61 cm', Weight: '900g', 'Non-slip': 'Both sides' },
    tags: ['yoga mat', 'yoga', 'fitness', 'pilates', 'exercise', 'non-slip'],
    colors: ['Purple', 'Teal', 'Black', 'Rose'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '1 year quality guarantee',
    returnPolicy: '15-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Meenakshi B.', rating: 5, title: 'Best mat I\'ve used', comment: 'The grip is incredible — no slipping even when sweaty.', verified: true, date: '2025-08-12' },
    ],
  },
  {
    sku: 32,
    name: 'Resistance Band Set',
    brand: 'FitCore',
    category: 'Sports',
    subcategory: 'Gym Equipment',
    price: 649,
    originalPrice: 899,
    costPrice: 250,
    inventory: 250,
    rating: 4.5,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
    description: 'Set of 5 latex resistance bands — light to extra-heavy for all levels.',
    features: ['5 resistance levels (2–25kg)', 'Natural latex construction', 'Includes carry bag', 'Suitable for home workouts', 'Anti-snap guarantee'],
    specifications: { 'Set': '5 bands', Material: 'Natural Latex', 'Resistance': '2, 5, 10, 15, 25kg', 'Anti-snap': 'Yes' },
    tags: ['resistance bands', 'gym', 'home workout', 'strength training', 'fitness'],
    colors: ['Multi-color set'],
    delivery: 'Free delivery in 2–4 working days',
    returnPolicy: '15-day easy returns',
    reviews: [
      { user: 'Rohan D.', rating: 5, title: 'Excellent for home gym', comment: 'Great quality. The 25kg band is genuinely challenging.', verified: true, date: '2025-07-30' },
    ],
  },
  {
    sku: 33,
    name: 'Cricket Bat Premium',
    brand: 'SportsKing',
    category: 'Sports',
    subcategory: 'Cricket',
    price: 3499,
    originalPrice: 4500,
    costPrice: 2200,
    inventory: 35,
    rating: 4.6,
    reviewCount: 87,
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&q=80',
    description: 'Grade 1 English willow bat — ideal for leather ball cricket.',
    features: ['Grade 1 English Willow', 'Full size (SH)', 'Pre-knocked and oiled', 'Cane handle with twin grips'],
    specifications: { Willow: 'Grade 1 English', Size: 'SH (Short Handle)', Weight: '1.1–1.2kg', Handle: 'Cane with 2 grips' },
    tags: ['cricket bat', 'cricket', 'sports', 'english willow', 'leather ball'],
    delivery: 'Free delivery in 5–7 working days',
    warranty: '6 months manufacturer warranty',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Virat M.', rating: 5, title: 'Excellent pickup', comment: 'The balance and pickup are perfect. Beautiful edges.', verified: true, date: '2025-08-01' },
    ],
  },

  // ── NEW PRODUCTS — KIDS / TOYS ────────────────────────────────────────────
  {
    sku: 34,
    name: 'STEM Building Blocks Set',
    brand: 'KidZone',
    category: 'Toys',
    subcategory: 'Educational Toys',
    price: 1299,
    originalPrice: 1699,
    costPrice: 600,
    inventory: 100,
    rating: 4.8,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description: '250-piece magnetic building blocks — develops creativity and spatial thinking.',
    features: ['250 pieces', 'Strong neodymium magnets', 'Ages 3+', 'Non-toxic ABS plastic', 'Instruction booklet with 100 designs'],
    specifications: { Pieces: '250', Material: 'ABS Plastic', 'Age Group': '3+ years', Magnets: 'Neodymium' },
    tags: ['building blocks', 'STEM', 'magnetic', 'educational', 'kids', 'toys'],
    colors: ['Multi-color'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '1 year quality guarantee',
    returnPolicy: '15-day easy returns',
    reviews: [
      { user: 'Deepa V.', rating: 5, title: 'Kids love it', comment: 'Hours of entertainment. The magnets are strong and safe.', verified: true, date: '2025-08-14' },
    ],
  },
  {
    sku: 35,
    name: 'Remote Control Car',
    brand: 'KidZone',
    category: 'Toys',
    subcategory: 'RC Toys',
    price: 1799,
    originalPrice: 2299,
    costPrice: 900,
    inventory: 60,
    rating: 4.5,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600&q=80',
    description: 'High-speed RC car with 2.4GHz control and 30+ km/h top speed.',
    features: ['30+ km/h top speed', '2.4GHz interference-free control', '30-minute run time', '4WD off-road chassis', 'USB rechargeable battery'],
    specifications: { Speed: '30+ km/h', Control: '2.4GHz', 'Run Time': '30 minutes', Drive: '4WD', 'Age Group': '6+ years' },
    tags: ['RC car', 'remote control', 'kids', 'toys', 'fast', '4WD'],
    colors: ['Red', 'Blue', 'Green'],
    delivery: 'Free delivery in 3–5 working days',
    returnPolicy: '7-day easy returns',
    isNew: true,
    reviews: [
      { user: 'Aakash K.', rating: 5, title: 'Great speed', comment: 'My son loves it. Really fast and the battery lasts a good while.', verified: true, date: '2025-08-09' },
    ],
  },

  // ── NEW PRODUCTS — BOOKS ──────────────────────────────────────────────────
  {
    sku: 36,
    name: 'Atomic Habits',
    brand: 'James Clear',
    category: 'Books',
    subcategory: 'Self-Help',
    price: 399,
    originalPrice: 599,
    costPrice: 150,
    inventory: 500,
    rating: 4.9,
    reviewCount: 2145,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80',
    description: 'The #1 international bestseller on building good habits and breaking bad ones.',
    features: ['336 pages', 'Paperback edition', 'International bestseller', 'Practical framework for habit change'],
    specifications: { Pages: '336', Format: 'Paperback', Language: 'English', Publisher: 'Penguin Random House', ISBN: '978-0735211292' },
    tags: ['book', 'self-help', 'habits', 'productivity', 'bestseller', 'James Clear'],
    delivery: 'Free delivery in 2–3 working days',
    returnPolicy: '7-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Kabir S.', rating: 5, title: 'Life-changing read', comment: 'The most practical book on habits I\'ve ever read. Already applying the 1% principle.', verified: true, date: '2025-08-15' },
    ],
  },
  {
    sku: 37,
    name: 'Deep Work',
    brand: 'Cal Newport',
    category: 'Books',
    subcategory: 'Productivity',
    price: 349,
    originalPrice: 499,
    costPrice: 130,
    inventory: 350,
    rating: 4.7,
    reviewCount: 1023,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
    description: 'Rules for focused success in a distracted world. A must-read for knowledge workers.',
    features: ['304 pages', 'Paperback edition', 'Wall Street Journal bestseller'],
    specifications: { Pages: '304', Format: 'Paperback', Language: 'English', Publisher: 'Grand Central Publishing' },
    tags: ['book', 'productivity', 'focus', 'work', 'Cal Newport', 'deep work'],
    delivery: 'Free delivery in 2–3 working days',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Nandita P.', rating: 5, title: 'Changed how I work', comment: 'Essential reading for anyone who does knowledge work.', verified: true, date: '2025-07-30' },
    ],
  },

  // ── NEW PRODUCTS — GROCERY / HEALTH ──────────────────────────────────────
  {
    sku: 38,
    name: 'Whey Protein Chocolate',
    brand: 'MuscleFuel',
    category: 'Grocery',
    subcategory: 'Protein Supplements',
    price: 1999,
    originalPrice: 2499,
    costPrice: 1100,
    inventory: 120,
    rating: 4.6,
    reviewCount: 567,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600&q=80',
    description: '1kg whey protein isolate — 25g protein per serving, chocolate flavour.',
    features: ['25g protein per serving', '<1g sugar per serving', '30 servings per pack', 'Informed Sport certified', 'BCAA and glutamine rich'],
    specifications: { Weight: '1kg', 'Protein per serving': '25g', Servings: '30', Flavour: 'Chocolate', 'Certification': 'Informed Sport' },
    tags: ['whey protein', 'protein', 'gym', 'supplement', 'chocolate', 'muscle'],
    delivery: 'Free delivery in 2–4 working days',
    returnPolicy: '15-day easy returns',
    reviews: [
      { user: 'Gaurav N.', rating: 5, title: 'Best protein at this price', comment: 'Mixability is excellent. Chocolate flavour isn\'t too sweet.', verified: true, date: '2025-08-10' },
    ],
  },
  {
    sku: 39,
    name: 'Organic Green Tea',
    brand: 'ZenBrew',
    category: 'Grocery',
    subcategory: 'Tea & Coffee',
    price: 299,
    originalPrice: 399,
    costPrice: 100,
    inventory: 400,
    rating: 4.5,
    reviewCount: 456,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80',
    description: 'Single-estate Darjeeling green tea — 50 pyramid bags. Fresh, grassy, antioxidant-rich.',
    features: ['50 pyramid teabags', 'Single-estate Darjeeling', 'High antioxidant content', 'No artificial flavours', 'FSSAI certified'],
    specifications: { Quantity: '50 bags', Origin: 'Darjeeling, India', Type: 'Green Tea', 'Caffeine': 'Low', 'Certification': 'FSSAI' },
    tags: ['green tea', 'organic', 'Darjeeling', 'antioxidant', 'healthy', 'tea'],
    delivery: 'Free delivery in 2–3 working days',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Swati B.', rating: 5, title: 'Refreshing taste', comment: 'Tastes very fresh. Perfect morning tea.', verified: true, date: '2025-08-08' },
    ],
  },

  // ── NEW PRODUCTS — HOME APPLIANCES ───────────────────────────────────────
  {
    sku: 40,
    name: 'Robot Vacuum Cleaner',
    brand: 'CleanAir',
    category: 'Appliances',
    subcategory: 'Vacuum Cleaners',
    price: 12999,
    originalPrice: 17999,
    costPrice: 9000,
    inventory: 20,
    rating: 4.6,
    reviewCount: 145,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description: 'Wi-Fi robot vacuum with LiDAR mapping, 2500Pa suction and auto-recharge.',
    features: ['LiDAR smart mapping', '2500Pa strong suction', 'Auto-recharge & resume', 'App + voice control', 'Works on carpet and hard floors'],
    specifications: { Suction: '2500Pa', Mapping: 'LiDAR', 'Run Time': '120 minutes', 'Dustbin': '500ml', Connectivity: 'Wi-Fi + App', Compatibility: 'Alexa, Google Home' },
    tags: ['robot vacuum', 'vacuum cleaner', 'smart home', 'LiDAR', 'Wi-Fi', 'cleaning'],
    colors: ['White', 'Black'],
    delivery: 'Free delivery in 5–7 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isNew: true,
    isFeatured: true,
    reviews: [
      { user: 'Prerna L.', rating: 5, title: 'Completely hands-free cleaning', comment: 'Maps my apartment perfectly. Hasn\'t missed a spot in 3 weeks.', verified: true, date: '2025-08-14' },
    ],
  },
  {
    sku: 41,
    name: 'Instant Pot Duo',
    brand: 'HomeChef',
    category: 'Appliances',
    subcategory: 'Kitchen Appliances',
    price: 5999,
    originalPrice: 7999,
    costPrice: 4000,
    inventory: 45,
    rating: 4.8,
    reviewCount: 678,
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
    description: '7-in-1 electric pressure cooker — pressure cook, slow cook, sauté and more.',
    features: ['7-in-1: pressure cook, slow cook, sauté, steam, rice, yoghurt, warm', '6-litre capacity', '14 smart programs', 'Delay start up to 24h', 'Dishwasher-safe inner pot'],
    specifications: { Capacity: '6 litres', Functions: '7-in-1', Programs: '14', 'Power': '1000W', 'Inner Pot': 'Stainless steel, dishwasher safe' },
    tags: ['pressure cooker', 'instant pot', 'kitchen', 'slow cooker', 'sauté', 'multi-cooker'],
    colors: ['Stainless Steel'],
    delivery: 'Free delivery in 5–7 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    isFeatured: true,
    reviews: [
      { user: 'Radha G.', rating: 5, title: 'Best kitchen purchase ever', comment: 'Makes cooking so much easier. Biryani in 30 minutes!', verified: true, date: '2025-08-12' },
    ],
  },
  {
    sku: 42,
    name: 'Electric Kettle Pro',
    brand: 'HomeChef',
    category: 'Appliances',
    subcategory: 'Kitchen Appliances',
    price: 1299,
    originalPrice: 1799,
    costPrice: 700,
    inventory: 110,
    rating: 4.6,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=600&q=80',
    description: '1.7L variable temperature kettle with 6 presets — perfect for tea and coffee.',
    features: ['1.7L capacity', '6 temperature presets (60–100°C)', '360° base', 'Keep warm 30 min', 'Food-grade stainless interior'],
    specifications: { Capacity: '1.7 litres', 'Temperature Presets': '6 (60, 70, 80, 85, 90, 100°C)', Power: '1800W', 'Keep Warm': '30 minutes' },
    tags: ['kettle', 'electric kettle', 'kitchen', 'tea', 'coffee', 'variable temperature'],
    colors: ['Stainless Steel', 'Matte Black'],
    delivery: 'Free delivery in 3–5 working days',
    warranty: '1 year manufacturer warranty',
    returnPolicy: '7-day easy returns',
    reviews: [
      { user: 'Kavya S.', rating: 5, title: 'Perfect for tea lovers', comment: 'The temperature presets make a real difference to the taste of green tea.', verified: true, date: '2025-08-10' },
    ],
  },
];

// ──────────────────────────────────────────────────────────────────────────────
async function main() {
  requireEnv(['MONGODB_URI']);
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('✅ Connected to MongoDB');

  // Drop and re-insert all products
  await Product.deleteMany({});
  await Product.insertMany(products);
  console.log(`✅ Seeded ${products.length} products (with brands, features, specs & reviews)`);

  // Upsert merchant settings
  await MerchantSettings.findOneAndUpdate(
    {},
    DEFAULT_SETTINGS,
    { upsert: true, new: true, setDefaultsOnInsert: true }
  );
  console.log('✅ Seeded merchant settings:', DEFAULT_SETTINGS);

  await mongoose.disconnect();
  console.log('\n🎉 Seed complete.');
  process.exit(0);
}

main().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
